services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - 3001:3000
    networks:
      - backend-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_dist:/app/dist
    networks:
      - frontend-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    networks:
      - frontend-network
      - backend-network
    restart: always
    volumes:
      - frontend_dist:/var/www
      - ./backend/public:/var/www/backend

volumes:
  postgres_data:
  frontend_dist:

networks:
  backend-network:
  frontend-network:


# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: rootpassword
#       MONGO_INITDB_DATABASE: admin
#     restart: always
#     volumes:
#       - mongo_data:/data/db
#       - ./backend/test/mongodb_initial_stub.json:/docker-entrypoint-initdb.d/mongodb_initial_stub.json
#       - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
#     ports:
#       - 27017:27017
#     networks:
#       - mongo-network

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     env_file:
#       - backend/.env
#     ports:
#       - 3001:3000
#     networks:
#       - backend-network
#       - mongo-network
#     depends_on:
#       - mongo

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     volumes:
#       - frontend_dist:/app/dist
#     networks:
#       - frontend-network

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - 80:80
#     networks:
#       - frontend-network
#       - backend-network
#     restart: always
#     volumes:
#       - frontend_dist:/var/www
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./backend/public:/var/www/backend

# volumes:
#   mongo_data:
#   frontend_dist:

# networks:
#   backend-network:
#   mongo-network:
#   frontend-network:



# services:
#   database:
#     image: postgres:16.4
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_NAME: ${DB_NAME}
#     volumes:
#       - db_data:/var/lib/postgresql/data
#       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#     ports:
#       - '5432:5432'
#     networks:
#       - internal

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4_container
#     restart: always
#     ports:
#       - '5050:80'
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     networks:
#       - internal

#   frontend:
#     image: 'ghcr.io/${OWNER}/film-react-nest_frontend:latest'
#     build:
#       context: frontend
#     environment:
#       VITE_BASE_URL: /
#       VITE_API_URL: ${VITE_API_URL}
#       VITE_CDN_URL: ${VITE_CDN_URL}
#     volumes:
#       - frontend_build:/app/dist
#     networks:
#       - internal

#   backend:
#     image: 'ghcr.io/${OWNER}/film-react-nest_backend:latest'
#     build:
#       context: backend
#     environment:
#       PORT: ${PORT}
#       DEBUG: ${DEBUG}
#       DB_DRIVER: ${DB_DRIVER}
#       DB_HOST: ${DB_HOST}
#       DB_PORT: ${DB_PORT}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_NAME: ${DB_NAME}
#     ports:
#       - 3000:3000
#     networks:
#       - internal
#     depends_on:
#       - database

#   server:
#     image: 'ghcr.io/${OWNER}/film-react-nest_server:latest'
#     build:
#       context: nginx
#     ports:
#       - 80:80
#     volumes:
#       - frontend_build:/var/www
#     depends_on:
#       - frontend
#       - backend
#     networks:
#       - internal

# volumes:
#   db_data:
#   pgadmin-data:
#   frontend_build:

# networks:
#   internal:
